### ISSUE TITLE
Current travis config deploys 2 times

### ISSUE THREAD

**Issue by eifinger** [flopp/fritz-switch-profiles#5]
The current travis configuration tries to deploy for the 3.5 and 3.6 build. The one executed last fails to deploy because it can't overwrite the already deployed version on pypi.

I am no expert on this, maybe https://docs.travis-ci.com/user/build-stages could solve this

**Comment by flopp** [comment]
I've changed the `deploy` step, such that only the Python 3.6 version is deployed:

```
deploy:
  provider: pypi
  user: $PYPIUSER
  password: $PYPIPASSWORD
  on:
    branch: master
    python: "3.6"
```

7b5939d1b9df8c6ded665c68fae9bd2e54dc30c4
